format_version: 10
pipelines:
  pipeline-code:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2f525f2:
        git: https://github.com/valkyr13/Person-Search-using-NLP.git
        username: valkyr13
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:sOqzfrNrbAqDrjvKxeGWKg==:PeZSqH5notasrkh7HYowIw==
    stages:
    - testing-code:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                - there
                command: echo
                run_if: passed
          resources:
            - windows

